#!/bin/bash -e

# Enable jemalloc for reduced memory usage and latency.
if [ -z "${LD_PRELOAD+x}" ]; then
    LD_PRELOAD=$(find /usr/lib -name libjemalloc.so.2 -print -quit)
    export LD_PRELOAD
fi

# If running the rails server then cleanup stale pid and prepare DB
# If first args are rails server, clean pid and prepare DB
if { [ "$1" = "./bin/rails" ] || [ "$1" = "bin/rails" ]; } && [ "$2" = "server" ]; then
  rm -f tmp/pids/server.pid
  ./bin/rails db:prepare
fi

exec "${@}"
